//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Resources.Languages {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ejemplo.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DeleteButtonTitle {
            get {
                return ResourceManager.GetString("DeleteButtonTitle", resourceCulture);
            }
        }
        
        internal static string EditButtonTitle {
            get {
                return ResourceManager.GetString("EditButtonTitle", resourceCulture);
            }
        }
        
        internal static string DeleteItemTitle {
            get {
                return ResourceManager.GetString("DeleteItemTitle", resourceCulture);
            }
        }
        
        internal static string DeleteItemMessage {
            get {
                return ResourceManager.GetString("DeleteItemMessage", resourceCulture);
            }
        }
        
        internal static string YesDialog {
            get {
                return ResourceManager.GetString("YesDialog", resourceCulture);
            }
        }
        
        internal static string NoDialog {
            get {
                return ResourceManager.GetString("NoDialog", resourceCulture);
            }
        }
        
        internal static string ListViewExamplePageTitle {
            get {
                return ResourceManager.GetString("ListViewExamplePageTitle", resourceCulture);
            }
        }
        
        internal static string EditItemPageTitle {
            get {
                return ResourceManager.GetString("EditItemPageTitle", resourceCulture);
            }
        }
        
        internal static string EditItemTitle {
            get {
                return ResourceManager.GetString("EditItemTitle", resourceCulture);
            }
        }
        
        internal static string EditItemDescription {
            get {
                return ResourceManager.GetString("EditItemDescription", resourceCulture);
            }
        }
        
        internal static string EditItemMessage {
            get {
                return ResourceManager.GetString("EditItemMessage", resourceCulture);
            }
        }
        
        internal static string CancelItemTitle {
            get {
                return ResourceManager.GetString("CancelItemTitle", resourceCulture);
            }
        }
        
        internal static string CancelItemMessage {
            get {
                return ResourceManager.GetString("CancelItemMessage", resourceCulture);
            }
        }
        
        internal static string AddItemTitle {
            get {
                return ResourceManager.GetString("AddItemTitle", resourceCulture);
            }
        }
        
        internal static string AddItemMessage {
            get {
                return ResourceManager.GetString("AddItemMessage", resourceCulture);
            }
        }
        
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
    }
}
